# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LCAcov <- function(mY, mZ, iK, mPhi, mBeta, mStep1Var, fixed = 0L, maxIter = 1e3L, tol = 1e-8, NRtol = 1e-6, NRmaxit = 100L) {
    .Call('_multilevLCA_LCAcov', PACKAGE = 'multilevLCA', mY, mZ, iK, mPhi, mBeta, mStep1Var, fixed, maxIter, tol, NRtol, NRmaxit)
}

LCA <- function(mY, iK, mU, maxIter = 1e3L, tol = 1e-8, reord = 0L) {
    .Call('_multilevLCA_LCA', PACKAGE = 'multilevLCA', mY, iK, mU, maxIter, tol, reord)
}

LCA_fast <- function(mY, ivFreq, iK, mU, maxIter = 1e3L, tol = 1e-8, reord = 0L) {
    .Call('_multilevLCA_LCA_fast', PACKAGE = 'multilevLCA', mY, ivFreq, iK, mU, maxIter, tol, reord)
}

LCA_LLK <- function(parvec, mY, iK) {
    .Call('_multilevLCA_LCA_LLK', PACKAGE = 'multilevLCA', parvec, mY, iK)
}

LCA_LLK_j <- function(parvec, mY, iK) {
    .Call('_multilevLCA_LCA_LLK_j', PACKAGE = 'multilevLCA', parvec, mY, iK)
}

MixtDensityScale <- function(vOmega, vD_log, iJ) {
    .Call('_multilevLCA_MixtDensityScale', PACKAGE = 'multilevLCA', vOmega, vD_log, iJ)
}

rando_index <- function(p) {
    .Call('_multilevLCA_rando_index', PACKAGE = 'multilevLCA', p)
}

zero_bound <- function(parvec, zbound = 1e-04) {
    .Call('_multilevLCA_zero_bound', PACKAGE = 'multilevLCA', parvec, zbound)
}

logisticReg <- function(vY, vZ, SmoothProb, vBeta, maxIter = 5L, tol = 1e-5) {
    .Call('_multilevLCA_logisticReg', PACKAGE = 'multilevLCA', vY, vZ, SmoothProb, vBeta, maxIter, tol)
}

NR_step_cov <- function(mX, mbeta, mU) {
    .Call('_multilevLCA_NR_step_cov', PACKAGE = 'multilevLCA', mX, mbeta, mU)
}

NR_step_covIT <- function(mX, mbeta, mU, tol = 1e-06, maxIt = 100L) {
    .Call('_multilevLCA_NR_step_covIT', PACKAGE = 'multilevLCA', mX, mbeta, mU, tol, maxIt)
}

NR_step_covIT_wei <- function(mX, mbeta, mU, vWei, tol = 1e-06, maxIt = 100L) {
    .Call('_multilevLCA_NR_step_covIT_wei', PACKAGE = 'multilevLCA', mX, mbeta, mU, vWei, tol, maxIt)
}

vecTomatClass <- function(vClass) {
    .Call('_multilevLCA_vecTomatClass', PACKAGE = 'multilevLCA', vClass)
}

AvgMarginalEff <- function(beta, P_ij, weights) {
    .Call('_multilevLCA_AvgMarginalEff', PACKAGE = 'multilevLCA', beta, P_ij, weights)
}

MLTLCA_covlowhigh <- function(mY, mZ, mZh, vNj, mDelta_start, cGamma_start, mPhi_start, mStep1Var, maxIter = 1e3L, tol = 1e-8, fixedpars = 0L, NRtol = 1e-6, NRmaxit = 100L) {
    .Call('_multilevLCA_MLTLCA_covlowhigh', PACKAGE = 'multilevLCA', mY, mZ, mZh, vNj, mDelta_start, cGamma_start, mPhi_start, mStep1Var, maxIter, tol, fixedpars, NRtol, NRmaxit)
}

MLTLCA_cov <- function(mY, mZ, vNj, vOmega_start, cGamma_start, mPhi_start, mStep1Var, maxIter = 1e3L, tol = 1e-8, fixedpars = 0L, NRtol = 1e-6, NRmaxit = 100L) {
    .Call('_multilevLCA_MLTLCA_cov', PACKAGE = 'multilevLCA', mY, mZ, vNj, vOmega_start, cGamma_start, mPhi_start, mStep1Var, maxIter, tol, fixedpars, NRtol, NRmaxit)
}

MLTLCA <- function(mY, vNj, vOmega, mPi, mPhi, maxIter = 1e3L, tol = 1e-8, reord = 1L) {
    .Call('_multilevLCA_MLTLCA', PACKAGE = 'multilevLCA', mY, vNj, vOmega, mPi, mPhi, maxIter, tol, reord)
}

MLTLCA_cov_LLK <- function(parvec, mY, mZ, vNj, iM, iT) {
    .Call('_multilevLCA_MLTLCA_cov_LLK', PACKAGE = 'multilevLCA', parvec, mY, mZ, vNj, iM, iT)
}

MLTLCA_cov_LLK_j <- function(parvec, mY, mZ, vNj, iM, iT) {
    .Call('_multilevLCA_MLTLCA_cov_LLK_j', PACKAGE = 'multilevLCA', parvec, mY, mZ, vNj, iM, iT)
}

MLTLCA_LLK <- function(parvec, mY, vNj, iM, iT) {
    .Call('_multilevLCA_MLTLCA_LLK', PACKAGE = 'multilevLCA', parvec, mY, vNj, iM, iT)
}

MLTLCA_LLK_j <- function(parvec, mY, vNj, iM, iT) {
    .Call('_multilevLCA_MLTLCA_LLK_j', PACKAGE = 'multilevLCA', parvec, mY, vNj, iM, iT)
}

